'use strict';
// Public app: no personal dataset is bundled or requested from a server.
const $ = id => document.getElementById(id);
const KEY = 'mhl-visitor-plan-v1';
const TEMPLATE = {meta:{version:1},loan:{lender:'',interestType:'Floating',projectCost:0,sanctioned:0,disbursed:0,outstanding:0,rate:0,tenureYears:15,repaymentStart:'',extraMonthly:0,notes:''},contractor:[],indirectExpenses:[],disbursements:[],prepayments:[],budget:[],indirectBudget:[],funding:[],processing:{stage:''},emergency:{monthlyEssentials:0,targetMonths:0,currentFund:0},family:[],insurance:[],actions:[],strategy:{},life:{educationMonthly:0,parentsCareMonthly:0,healthReserve:0,annualInflation:5}};
let plan = null, tab = 'overview', source = 'blank';
const money = n => '₹' + (Number(n)||0).toLocaleString('en-IN',{maximumFractionDigits:0});
const sum = (rows, field='amount') => (Array.isArray(rows)?rows:[]).reduce((a,x)=>a+(Number(x[field])||0),0);
const esc = v => String(v??'').replace(/[&<>"']/g, ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));
const asArray = v => Array.isArray(v)?v:[];
function validate(raw){if(!raw||typeof raw!=='object'||Array.isArray(raw))throw Error('This is not a loan-plan JSON object.');if(raw.loan&&!['object'].includes(typeof raw.loan))throw Error('The loan field must be an object.');for(const k of ['contractor','indirectExpenses','disbursements','prepayments','budget','indirectBudget','funding','family','insurance','actions'])if(raw[k]!=null&&!Array.isArray(raw[k]))throw Error(`${k} should be a list.`);return {...structuredClone(TEMPLATE),...raw,loan:{...TEMPLATE.loan,...(raw.loan||{})}}}
function notify(text){$('notice').textContent=text;}
function show(p,label){plan=validate(p);source=label;document.querySelector('#workspace').hidden=false;document.querySelector('#intro').hidden=true;$('source-label').textContent=label==='blank'?'A fresh plan, saved on this device':label==='import'?'Imported JSON · kept in this browser':'Saved on this device';render();$('workspace').scrollIntoView({behavior:'smooth'});}
function save(){if(window.planOrigin==='owner'){notify('This private plan is read-only. No changes were saved.');return}try{localStorage.setItem(KEY,JSON.stringify(plan));notify('Saved on this device. Export JSON to keep a backup.')}catch{notify('Browser storage is unavailable. Export JSON now to keep a copy.')}render()}
function download(obj,name){const blob=new Blob([JSON.stringify(obj,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
if($('start')) $('start').onclick=()=>{show(TEMPLATE,'blank');save()};$('import').onclick=()=>$('file').click();$('file').onchange=async e=>{const f=e.target.files?.[0];if(!f)return;if(f.size>5_000_000){alert('This file is larger than 5 MB. Please choose a smaller JSON plan.');return}try{show(JSON.parse(await f.text()),'import');save()}catch(err){alert('Could not open this plan: '+err.message)}e.target.value=''};
$('template').onclick=()=>download(TEMPLATE,'my-home-loan-empty-template.json');$('download').onclick=()=>{if(window.planOrigin==='owner'){notify('Private-plan export is disabled in this preview.');return}if(plan)download(plan,'my-home-loan-backup.json')};$('reset').onclick=()=>{if(window.planOrigin==='owner'){notify('Use Sign out to close your private plan.');return}if(!confirm('Close this plan and delete its saved copy from this browser? Export a backup first if you need it.'))return;localStorage.removeItem(KEY);plan=null;$('workspace').hidden=true;$('intro').hidden=false;window.scrollTo({top:0,behavior:'smooth'})};
document.querySelectorAll('.tabs button').forEach(b=>b.onclick=()=>{tab=b.dataset.tab;render()});
function card(label,value,sub=''){return `<div class="card"><label>${esc(label)}</label><strong>${esc(value)}</strong><small>${esc(sub)}</small></div>`}
function bars(rows){if(!rows.length)return '<div class="empty">No entries yet. Import a JSON plan to see the breakdown.</div>';const max=Math.max(1,...rows.map(x=>Number(x.value)||0));return rows.map(x=>`<div class="bar-row"><span>${esc(x.label)}</span><div class="bar"><i style="width:${Math.min(100,Math.max(0,(Number(x.value)||0)/max*100))}%"></i></div><b>${esc(money(x.value))}</b></div>`).join('')}
function table(rows,fields){if(!rows.length)return '<div class="empty">No records in this section yet.</div>';return `<div class="table-wrap"><table><thead><tr>${fields.map(f=>`<th>${esc(f.label)}</th>`).join('')}</tr></thead><tbody>${rows.map(row=>`<tr>${fields.map(f=>`<td>${esc(f.render?f.render(row):row[f.key])}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`}
const cost=()=>sum(plan.contractor)+sum(plan.indirectExpenses);
function overview(){const l=plan.loan,costPlanned=sum(plan.budget,'planned')+sum(plan.indirectBudget,'planned'),fund=sum(plan.funding,'planned'),out=Number(l.outstanding)||0,rate=Number(l.rate)||0;return `<div class="cards">${card('Project budget',money(costPlanned),'Construction + indirect')}${card('Paid to date',money(cost()),'Contractor + indirect')}${card('Loan outstanding',money(out),'Entered balance')}${card('Remaining budget',money(costPlanned-cost()),'Plan minus paid')}</div><div class="grid2"><div class="panel"><h3>Funding plan</h3>${bars(asArray(plan.funding).map(x=>({label:x.source||'Other',value:x.planned})))}</div><div class="panel"><h3>What needs attention</h3><p>Funding gap: <strong>${money(costPlanned-fund)}</strong> · ${costPlanned>fund?'planned budget exceeds listed sources':'planned sources cover listed budget'}</p><p>Processing stage: <span class="pill">${esc(plan.processing?.stage||'Not set')}</span></p><p>Interest rate: <strong>${esc(rate)}%</strong> · Entered lender: <strong>${esc(l.lender||'Not set')}</strong></p><p class="hint">Figures are only as current as the JSON you imported or the edits on this device.</p></div></div>`}
function ledger(){return `<div class="cards">${card('Contractor paid',money(sum(plan.contractor)),`${asArray(plan.contractor).length} entries`)}${card('Indirect costs',money(sum(plan.indirectExpenses)),`${asArray(plan.indirectExpenses).length} entries`)}${card('Disbursed',money(sum(plan.disbursements)),'Recorded disbursements')}${card('Prepaid',money(sum(plan.prepayments)),'Recorded extra payments')}</div><div class="panel"><h3>Contractor payments</h3>${table(asArray(plan.contractor),[{key:'date',label:'Date'},{key:'payee',label:'Payee'},{key:'category',label:'Category'},{key:'source',label:'Source'},{key:'amount',label:'Amount',render:x=>money(x.amount)}])}</div><div class="panel"><h3>Indirect expenses</h3>${table(asArray(plan.indirectExpenses),[{key:'date',label:'Date'},{key:'description',label:'Description'},{key:'category',label:'Category'},{key:'amount',label:'Amount',render:x=>money(x.amount)}])}</div>`}
function plans(){return `<div class="grid2"><div class="panel"><h3>Construction budget</h3>${bars(asArray(plan.budget).map(x=>({label:x.category||'Other',value:x.planned})))}</div><div class="panel"><h3>Indirect cost budget</h3>${bars(asArray(plan.indirectBudget).map(x=>({label:x.category||'Other',value:x.planned})))}</div></div><div class="panel"><h3>Funding sources</h3>${table(asArray(plan.funding),[{key:'source',label:'Source'},{key:'note',label:'Notes'},{key:'planned',label:'Planned',render:x=>money(x.planned)}])}</div>`}
function sim(balance,rate,years,extra){const r=rate/1200,months=Math.max(1,Math.round(years*12));if(balance<=0||years<=0||rate<0||rate>100)return null;const emi=r?balance*r/(1-(1+r)**(-months)):balance/months;if(!Number.isFinite(emi))return null;let b=balance,interest=0,m=0;while(b>.01&&m<1200){let charge=b*r;interest+=charge;const payment=Math.min(b+charge,emi+extra);b=Math.max(0,b+charge-payment);m++;if(payment<=charge)return null}return {emi,interest,months:m,finish:b<.01}}
function schedule(){let l=plan.loan;return `<div class="panel"><h3>Loan payoff scenario</h3><p class="hint">Uses a fixed monthly rate for an estimate, not the lender's actual floating-rate or construction-linked schedule. It starts from the balance entered below, not sanctioned amount; excludes fees and future disbursements.</p><div class="fields"><label>Outstanding balance (₹)<input id="outstanding" type="number" min="0" value="${esc(l.outstanding||0)}"></label><label>Annual interest (%)<input id="rate" type="number" min="0" max="100" step=".01" value="${esc(l.rate||0)}"></label><label>Remaining term (years)<input id="tenureYears" type="number" min=".1" max="100" step=".1" value="${esc(l.tenureYears||15)}"></label><label>Extra each month (₹)<input id="extraMonthly" type="number" min="0" value="${esc(l.extraMonthly||0)}"></label></div><button class="primary" id="calculate">Update scenario</button><div id="simulation"></div></div>`}
function updateSimulation(){const l=plan.loan,b=Number(l.outstanding),r=Number(l.rate),y=Number(l.tenureYears),extra=Number(l.extraMonthly),base=sim(b,r,y,0),scenario=sim(b,r,y,extra);$('simulation').innerHTML=(!base||!scenario)?'<p class="alert">Enter a positive outstanding balance and a valid interest rate/term to compare payments.</p>':`<div class="cards" style="margin-top:22px">${card('Baseline EMI',money(base.emi),'Constant-rate estimate')}${card('Baseline payoff',`${base.months} months`,money(base.interest)+' interest')}${card('With extra payment',`${scenario.months} months`,money(scenario.interest)+' interest')}${card('Estimated saving',money(base.interest-scenario.interest),`${base.months-scenario.months} months earlier`)}</div><p class="hint">Rate changes, payment dates, lender rounding and future disbursements will change actual results.</p>`}
function records(){return `<div class="grid2"><div class="panel"><h3>Emergency reserve</h3><p>Current: <strong>${money(plan.emergency?.currentFund)}</strong></p><p>Target: <strong>${money(Number(plan.emergency?.monthlyEssentials||0)*Number(plan.emergency?.targetMonths||0))}</strong></p></div><div class="panel"><h3>Project details</h3><p>${esc(plan.loan.notes||'No project notes entered.')}</p></div></div><div class="panel"><h3>Family records</h3>${table(asArray(plan.family),[{key:'name',label:'Name'},{key:'relation',label:'Relation'},{key:'dependency',label:'Dependency'}])}</div><div class="panel"><h3>Insurance cover</h3>${table(asArray(plan.insurance),[{key:'name',label:'Name'},{key:'type',label:'Type'},{key:'sumInsured',label:'Cover',render:x=>money(x.sumInsured)}])}</div><div class="panel"><h3>Actions</h3>${table(asArray(plan.actions),[{key:'description',label:'Action'},{key:'status',label:'Status'}])}</div>`}
function render(){if(!plan)return;document.querySelectorAll('.tabs button').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));$('view').innerHTML=({overview,ledger,plans,schedule,records}[tab])();if(tab==='schedule'){if(window.planOrigin==='owner')$('calculate').disabled=true;$('calculate').onclick=()=>{if(window.planOrigin==='owner'){notify('Private plan is read-only in this preview.');return}for(const k of ['outstanding','rate','tenureYears','extraMonthly']){let n=Number($(k).value);if(!Number.isFinite(n)||n<0){notify('Enter non-negative numbers.');return}plan.loan[k]=n}save()};updateSimulation()}}
try{const stored=localStorage.getItem(KEY);if(stored){show(JSON.parse(stored),'saved');notify('This browser has a saved plan. It has not been uploaded.')}}catch{localStorage.removeItem(KEY)}
// Editable local plan. Additions are saved only on this device and to explicit downloads.
const editFields={loan:[['lender','Lender','text'],['loanAccountNumber','Loan account number','text'],['projectCost','Project cost (₹)','number'],['sanctioned','Sanctioned loan (₹)','number'],['disbursed','Total disbursed (₹)','number'],['outstanding','Outstanding loan (₹)','number'],['rate','Annual rate (%)','number'],['tenureYears','Remaining term (years)','number'],['repaymentStart','Repayment start','date'],['emiDueDay','EMI due day','number'],['extraMonthly','Extra monthly payment (₹)','number'],['annualLumpSum','Annual lump sum (₹)','number'],['lumpSumMonth','Lump-sum month (1-12)','number'],['emiStepUpPercent','Annual EMI step-up (%)','number'],['targetDebtFree','Target debt-free date','date'],['preEmiUntil','Full EMI transition date','date'],['notes','Project notes','text']],emergency:[['monthlyEssentials','Monthly essentials (₹)','number'],['targetMonths','Reserve months','number'],['currentFund','Current reserve (₹)','number'],['monthlyContribution','Monthly contribution (₹)','number'],['sinkingFund','Other sinking funds (₹)','number']]};
const entryFields={contractor:[['date','Date','date'],['payee','Payee','text'],['category','Category','text'],['amount','Amount (₹)','number'],['source','Funding source','text'],['mode','Payment mode','text'],['note','Reference / note','text']],indirectExpenses:[['date','Date','date'],['description','Description','text'],['category','Category','text'],['amount','Amount (₹)','number'],['source','Funding source','text']],budget:[['category','Category','text'],['planned','Budget (₹)','number']],indirectBudget:[['category','Category','text'],['planned','Budget (₹)','number']],funding:[['source','Source','text'],['planned','Planned (₹)','number']],disbursements:[['date','Date','date'],['amount','Amount (₹)','number'],['note','Reference / note','text']],prepayments:[['date','Date','date'],['amount','Amount (₹)','number'],['note','Reference / note','text']],actions:[['description','Action','text'],['status','Status','text']],insurance:[['name','Policy name','text'],['type','Type','text'],['provider','Provider','text'],['sumInsured','Cover (₹)','number'],['premium','Premium (₹)','number'],['renewal','Renewal','date']],family:[['name','Name','text'],['relation','Relationship','text'],['dependency','Dependency','text']]};
function fieldsFor(def,prefix,obj){return def.map(([key,label,type])=>`<label>${esc(label)}<input data-key="${esc(key)}" id="${prefix}${esc(key)}" type="${type}" ${type==='number'?'min="0" step="any"':''} value="${esc(obj?.[key]??'')}"></label>`).join('')}
function edit(){return `<div class="panel"><h3>Loan details</h3><div class="editor">${fieldsFor(editFields.loan,'loan-',plan.loan)}</div><div class="editor-actions"><button class="primary" id="save-loan">Save loan details</button></div></div><div class="panel"><h3>Emergency reserve</h3><div class="editor">${fieldsFor(editFields.emergency,'emergency-',plan.emergency||{})}</div><div class="editor-actions"><button class="primary" id="save-emergency">Save reserve</button></div></div><div class="panel"><h3>Ledger and planning entries</h3><p class="hint">Add an entry to your plan, then export a backup. Editing a JSON import stays local to this browser. Frozen records from an imported plan are read-only here; change them in your source of truth.</p><label>Section<select id="entry-section">${Object.keys(entryFields).map(k=>`<option value="${k}">${esc(({indirectExpenses:'Indirect expenses',indirectBudget:'Indirect budget'}[k]||k))}</option>`).join('')}</select></label><div id="entry-fields" class="editor" style="margin-top:20px"></div><div class="editor-actions"><button class="primary" id="add-entry">Add entry</button></div><div id="entry-list"></div></div>`}
function mountEdit(){for(const section of Object.keys(editFields)){$('save-'+section).onclick=()=>{const obj=plan[section]||(plan[section]={});for(const [key,label,type] of editFields[section]){const val=$(section+'-'+key).value;if(type==='number'&&(!Number.isFinite(Number(val))||Number(val)<0)){notify(`${label} must be a non-negative number.`);return}obj[key]=type==='number'?Number(val):val}save()}}const selector=$('entry-section');function updateSection(){const section=selector.value,def=entryFields[section];$('entry-fields').innerHTML=fieldsFor(def,'entry-',{});const rows=asArray(plan[section]);$('entry-list').innerHTML=rows.length?`<div class="table-wrap"><table><thead><tr>${def.map(x=>`<th>${esc(x[1])}</th>`).join('')}<th></th></tr></thead><tbody>${rows.map((row,i)=>`<tr>${def.map(([key,,type])=>`<td>${esc(type==='number'?money(row[key]):row[key])}</td>`).join('')}<td>${row.frozen?'<span class="pill">Frozen</span>':`<button class="row-delete" data-index="${i}">Remove</button>`}</td></tr>`).join('')}</tbody></table></div>`:'<div class="empty-state">No entries yet.</div>';$('entry-list').querySelectorAll('button[data-index]').forEach(b=>b.onclick=()=>{if(!confirm('Remove this entry?'))return;plan[section].splice(Number(b.dataset.index),1);save()})}selector.onchange=updateSection;updateSection();$('add-entry').onclick=()=>{const section=selector.value,row={};for(const [key,label,type] of entryFields[section]){const value=$('entry-'+key).value;if(type==='number'&&(!Number.isFinite(Number(value))||Number(value)<0)){notify(`${label} must be a non-negative number.`);return}row[key]=type==='number'?Number(value):value}if(!Object.values(row).some(v=>v&&v!==0)){notify('Enter at least one field to add an entry.');return}plan[section]=asArray(plan[section]);plan[section].push(row);save()}}
// Replace the first render implementation with an extension preserving the existing views.
const originalRender=render;
render=function(){if(!plan)return;if(tab==='edit'&&window.planOrigin==='owner'){tab='overview';notify('Private plan is read-only in this preview.')}if(tab==='edit'){document.querySelectorAll('.tabs button').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));$('view').innerHTML=edit();mountEdit()}else originalRender()};

window.show=show;window.clearLoadedPlan=()=>{plan=null;document.getElementById('workspace').hidden=true;document.getElementById('intro').hidden=false};
// Native full-depth workspace extension. Every visitor mutation is local-only.
const UI={section:'contractor',editIndex:null};
const SECTIONS={contractor:'Contractor payment',indirectExpenses:'Indirect expense',budget:'Direct budget category',indirectBudget:'Indirect budget category',funding:'Funding source',disbursements:'Loan disbursement',prepayments:'Prepayment',actions:'Follow-up action',insurance:'Insurance policy',family:'Family member'};
const INSURANCE_FULL=[['name','Policy name','text'],['type','Type','text'],['structure','Structure','text'],['covers','Who or what it covers','text'],['provider','Provider','text'],['sumInsured','Sum insured (₹)','number'],['deductible','Deductible (₹)','number'],['premium','Premium (₹)','number'],['renewal','Renewal date','date'],['notes','Exclusions, nominees and notes','text']];
const ACTIONS_FULL=[['title','What needs to happen?','text'],['due','Due date','date'],['owner','Who is responsible?','text'],['status','Status','text'],['category','Category','text'],['note','Next step / reference','text']];
const FAMILY_FULL=[['name','Name','text'],['relation','Relationship','text'],['dob','Date of birth','date'],['dependency','Role / dependency','text'],['notes','Notes','text']];
const ENTRY_FULL={...entryFields,insurance:INSURANCE_FULL,actions:ACTIONS_FULL,family:FAMILY_FULL,disbursements:[['date','Date','date'],['stage','Construction milestone','text'],['reference','Bank reference','text'],['amount','Amount (₹)','number']],prepayments:[['date','Date','date'],['source','Source','text'],['note','Note','text'],['amount','Amount (₹)','number']],budget:[['category','Direct construction category','text'],['planned','Planned amount (₹)','number'],['note','Scope note','text']],indirectBudget:[['category','Indirect / carrying cost category','text'],['planned','Planned amount (₹)','number'],['note','Assumption','text']],funding:[['source','Funding source','text'],['planned','Planned amount (₹)','number'],['note','Availability / conditions','text']],indirectExpenses:[['date','Date','date'],['description','Description','text'],['category','Indirect cost category','text'],['source','Funding source','text'],['note','Reference','text'],['amount','Amount (₹)','number']]};
const GO_TABS={loan:'edit',contractor:'ledger',insurance:'insurance'};
function goTo(section){if(window.planOrigin==='owner'){notify('Private data is read-only until cloud editing is tested.');return}if(!plan)show(TEMPLATE,'blank');UI.section=section;UI.editIndex=null;tab='edit';render();if(tab==='edit'){const sel=$('entry-section');if(sel&&ENTRY_FULL[section]){sel.value=section;sel.dispatchEvent(new Event('change'));requestAnimationFrame(()=>document.querySelector('#record-editor')?.scrollIntoView({behavior:'smooth',block:'start'}))}else requestAnimationFrame(()=>document.querySelector('#view')?.scrollIntoView({behavior:'smooth',block:'start'}))}}
document.querySelectorAll('[data-go]').forEach(b=>b.onclick=()=>goTo(b.dataset.go));
const priorShow=show;window.show=function(p,label){priorShow(p,label);if(label==='blank'){notify('Start with the actions above. Your changes save only on this device.');}};
function insuranceView(){const rows=asArray(plan.insurance),health=sum(rows.filter(x=>x.type==='Health'),'sumInsured'),life=sum(rows.filter(x=>x.type==='Term Life'),'sumInsured');const soon=rows.filter(x=>x.renewal&&new Date(x.renewal+'T00:00:00')>=new Date(new Date().toDateString())&&new Date(x.renewal+'T00:00:00')<new Date(Date.now()+30*86400000)).length;return `<div class="section-head"><div><h3>Insurance & protection</h3><p>List health, life and home cover. Record who is covered, the deductible, premium and renewal date.</p></div><button class="section-action" data-add="insurance">+ Add policy</button></div><div class="cards">${card('Health cover',money(health),`${rows.filter(x=>x.type==='Health').length} policies`)}${card('Term life cover',money(life),`${rows.filter(x=>x.type==='Term Life').length} policies`)}${card('Renewals in 30 days',String(soon),'Review dates')}${card('Policies',String(rows.length),'Your local register')}</div><div class="panel"><h3>Policy register</h3>${rows.length?rows.map((r,i)=>`<div class="policy-row"><div><strong>${esc(r.name||'Untitled policy')}</strong><div class="hint">${esc(r.type||'Other')} · ${esc(r.structure||'Structure not entered')} · ${esc(r.provider||'Provider not entered')}</div><div>Cover ${money(r.sumInsured)} · Premium ${money(r.premium)} · Renews ${esc(r.renewal||'date not entered')}</div><div class="hint">Covers: ${esc(r.covers||'Not entered')} · Deductible ${money(r.deductible)}${r.notes?` · ${esc(r.notes)}`:''}</div></div><div class="entry-tools">${r.frozen?'<span class="freeze-tag">Locked</span>':''}<button data-edit="insurance:${i}" ${r.frozen?'disabled':''}>Edit</button><button data-freeze="insurance:${i}">${r.frozen?'Unlock':'Lock'}</button><button data-delete="insurance:${i}" ${r.frozen?'disabled':''}>Delete</button></div></div>`).join(''):'<div class="empty"><p>No insurance policies yet.</p><p>Add any health, life or property cover you rely on, then check renewal dates.</p><button class="section-action" data-add="insurance">+ Add your first policy</button></div>'}</div>`}
function actionsAndFamilyView(){const family=asArray(plan.family),actions=asArray(plan.actions);return `<div class="grid2"><div class="panel"><div class="section-head"><div><h3>Family & co-applicants</h3><p>Keep the people affected by your plan together.</p></div><button class="section-action" data-add="family">+ Add person</button></div>${genericRows('family',family,['name','relation','dependency'])}</div><div class="panel"><div class="section-head"><div><h3>Follow-ups</h3><p>Bank paperwork, contractor milestones and renewals to chase.</p></div><button class="section-action" data-add="actions">+ Add action</button></div>${genericRows('actions',actions,['title','due','status'])}</div></div><div class="panel"><div class="section-head"><div><h3>Emergency reserve</h3><p>Keep a cash buffer before committing more to construction or prepayment.</p></div><button class="section-action" data-add="emergency">Edit reserve</button></div><p>Current ${money(plan.emergency?.currentFund)} · Target ${money(Number(plan.emergency?.monthlyEssentials||0)*Number(plan.emergency?.targetMonths||0))}</p></div>`}
function genericRows(section,rows,keys){return rows.length?rows.map((r,i)=>`<div class="policy-row"><div><strong>${esc(r[keys[0]]||'Untitled')}</strong><div class="hint">${esc(r[keys[1]]||'')} · ${esc(r[keys[2]]||'')}</div></div><div class="entry-tools">${r.frozen?'<span class="freeze-tag">Locked</span>':''}<button data-edit="${section}:${i}" ${r.frozen?'disabled':''}>Edit</button><button data-freeze="${section}:${i}">${r.frozen?'Unlock':'Lock'}</button><button data-delete="${section}:${i}" ${r.frozen?'disabled':''}>Delete</button></div></div>`).join(''):'<div class="empty">Nothing added yet.</div>'}
function bindEntryActions(){document.querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>goTo(b.dataset.add));for(const type of ['edit','freeze','delete'])document.querySelectorAll(`[data-${type}]`).forEach(b=>b.onclick=()=>{const [section,raw]=b.dataset[type].split(':'),i=Number(raw),row=plan[section]?.[i];if(!row)return;if(type==='edit'){if(row.frozen)return;goTo(section);UI.editIndex=i;const fields=ENTRY_FULL[section];for(const [key] of fields){const el=$('entry-'+key);if(el)el.value=row[key]??''}const add=$('add-entry');if(add)add.textContent='Save changes';notify(`Editing ${SECTIONS[section]}. Save changes below.`);return}if(type==='freeze'){if(!confirm(`${row.frozen?'Unlock':'Lock'} this ${SECTIONS[section]}? ${row.frozen?'It will become editable again.':'Edits and deletion will be blocked until you unlock it.'}`))return;row.frozen=!row.frozen;row.frozenAt=row.frozen?new Date().toISOString():null;save();return}if(type==='delete'){if(row.frozen)return;if(!confirm(`Delete this ${SECTIONS[section]}? This cannot be undone.`))return;plan[section].splice(i,1);save()}})}
// Render overrides keep overview/simulator, add visible contextual editing throughout.
const coreRender=render;
render=function(){if(!plan)return;if(tab==='insurance'){document.querySelectorAll('.tabs button').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));$('view').innerHTML=insuranceView();bindEntryActions();return}if(tab==='records'){document.querySelectorAll('.tabs button').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));$('view').innerHTML=actionsAndFamilyView();bindEntryActions();return}coreRender();if(tab==='ledger'||tab==='plans'||tab==='overview'){
  const view=$('view');if(tab==='ledger')view.insertAdjacentHTML('afterbegin',`<div class="section-head"><div><h3>Payments & cost control</h3><p>Direct payments go to the contractor ledger. Temporary rent, legal fees and carrying costs go to indirect costs.</p></div><div class="entry-tools"><button data-add="contractor">+ Contractor payment</button><button data-add="indirectExpenses">+ Indirect expense</button></div></div>`);
  if(tab==='plans')view.insertAdjacentHTML('afterbegin',`<div class="section-head"><div><h3>Budget, funding & disbursements</h3><p>Plan direct construction separately from indirect costs. Record bank releases by milestone, then compare funds with actual spend.</p></div><div class="entry-tools"><button data-add="budget">+ Direct budget</button><button data-add="indirectBudget">+ Indirect budget</button><button data-add="funding">+ Funding</button><button data-add="disbursements">+ Bank release</button></div></div>`);
  if(tab==='overview')view.insertAdjacentHTML('afterbegin',`<div class="section-head"><div><h3>Start with the full picture</h3><p>Enter the loan terms, budget and funding first. Keep the emergency reserve and insurance current before planning extra repayments.</p></div><button class="section-action" data-add="loan">Edit loan details</button></div>`);bindEntryActions();}}
const nativeEdit=edit;
edit=function(){let markup=nativeEdit();markup=markup.replace('<div class="panel"><h3>Ledger and planning entries</h3>','<div class="panel" id="record-editor"><h3>Add or update a record</h3>');return markup};
const nativeMountEdit=mountEdit;
mountEdit=function(){nativeMountEdit();const select=$('entry-section');if(!select)return;select.innerHTML=Object.keys(ENTRY_FULL).map(k=>`<option value="${k}">${esc(SECTIONS[k])}</option>`).join('');
  const nativeOnChange=select.onchange;
  select.onchange=()=>{UI.section=select.value;UI.editIndex=null;const fields=ENTRY_FULL[select.value];$('entry-fields').innerHTML=fieldsFor(fields,'entry-',{});$('add-entry').textContent='Add '+SECTIONS[select.value];$('entry-list').innerHTML=genericRows(select.value,asArray(plan[select.value]),fields.slice(0,3).map(x=>x[0]));bindEntryActions()};
  select.value=ENTRY_FULL[UI.section]?UI.section:'contractor';select.onchange();
  $('add-entry').onclick=()=>{const section=select.value,fields=ENTRY_FULL[section],row={};for(const [key,label,type] of fields){const input=$('entry-'+key),val=input?.value??'';if(type==='number'&&(!Number.isFinite(Number(val))||Number(val)<0)){notify(`${label} must be a non-negative number.`);return}row[key]=type==='number'?Number(val):val}if(!Object.values(row).some(v=>v!==''&&v!==0)){notify('Enter a value before saving.');return}plan[section]=asArray(plan[section]);const index=UI.editIndex;if(index!==null&&plan[section][index]&&!plan[section][index].frozen)plan[section][index]={...plan[section][index],...row,updatedAt:new Date().toISOString()};else plan[section].push({...row,frozen:false});UI.editIndex=null;save();notify(`Saved ${SECTIONS[section]} on this device.`)};
};

function lifePlan(){const x=plan.life||{};const baseline=Number(plan.emergency?.monthlyEssentials||0),extra=Number(x.educationMonthly||0)+Number(x.parentsCareMonthly||0),monthly=baseline+extra,months=Number(plan.emergency?.targetMonths||6),target=monthly*months+Number(x.healthReserve||0);return `<div class="panel"><div class="section-head"><div><h3>Life outside the loan</h3><p>Optional planning inputs. Keep essentials, children’s education and parents’ care in view before choosing an extra loan payment.</p></div></div><div class="editor">${[['educationMonthly','Children’s education per month (₹)','number'],['parentsCareMonthly','Parents’ care per month (₹)','number'],['healthReserve','Extra health reserve (₹)','number'],['annualInflation','Inflation assumption (%)','number']].map(([key,label,type])=>`<label>${esc(label)}<input id="life-${key}" type="${type}" min="0" step="any" value="${esc(x[key]??0)}"></label>`).join('')}</div><div class="editor-actions"><button class="primary" id="life-save">Save life planning</button></div><div class="mini-guide" style="margin-top:16px">With these inputs, a ${esc(months)}-month reserve target is ${money(target)}. This is a planning estimate; include only costs not already counted in monthly essentials to avoid double counting.</div></div>`}
const beforeRenderLife=render;
render=function(){beforeRenderLife();if(!plan)return;if(tab==='records'||tab==='schedule'){let view=$('view');view.insertAdjacentHTML('beforeend',lifePlan());$('life-save').onclick=()=>{if(window.planOrigin==='owner'){notify('Private plan read-only during testing.');return}plan.life=plan.life||{};for(const key of ['educationMonthly','parentsCareMonthly','healthReserve','annualInflation']){const n=Number($('life-'+key).value);if(!Number.isFinite(n)||n<0){notify('Use non-negative numbers.');return}plan.life[key]=n}save()}}};
