'use strict';
// Public app: no personal dataset is bundled or requested from a server.
const $ = id => document.getElementById(id);
const KEY = 'mhl-visitor-plan-v1';
const TEMPLATE = {meta:{version:1},loan:{lender:'',interestType:'Floating',projectCost:0,sanctioned:0,disbursed:0,outstanding:0,rate:0,tenureYears:15,repaymentStart:'',extraMonthly:0,notes:''},contractor:[],indirectExpenses:[],disbursements:[],prepayments:[],budget:[],indirectBudget:[],funding:[],processing:{stage:''},emergency:{monthlyEssentials:0,targetMonths:0,currentFund:0},family:[],insurance:[],actions:[],strategy:{}};
let plan = null, tab = 'overview', source = 'blank';
const money = n => '₹' + (Number(n)||0).toLocaleString('en-IN',{maximumFractionDigits:0});
const sum = (rows, field='amount') => (Array.isArray(rows)?rows:[]).reduce((a,x)=>a+(Number(x[field])||0),0);
const esc = v => String(v??'').replace(/[&<>"']/g, ch=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[ch]));
const asArray = v => Array.isArray(v)?v:[];
function validate(raw){if(!raw||typeof raw!=='object'||Array.isArray(raw))throw Error('This is not a loan-plan JSON object.');if(raw.loan&&!['object'].includes(typeof raw.loan))throw Error('The loan field must be an object.');for(const k of ['contractor','indirectExpenses','disbursements','prepayments','budget','indirectBudget','funding','family','insurance','actions'])if(raw[k]!=null&&!Array.isArray(raw[k]))throw Error(`${k} should be a list.`);return {...structuredClone(TEMPLATE),...raw,loan:{...TEMPLATE.loan,...(raw.loan||{})}}}
function notify(text){$('notice').textContent=text;}
function show(p,label){plan=validate(p);source=label;document.querySelector('#workspace').hidden=false;document.querySelector('#intro').hidden=true;$('source-label').textContent=label==='blank'?'A fresh plan, saved on this device':label==='import'?'Imported JSON · kept in this browser':'Saved on this device';render();$('workspace').scrollIntoView({behavior:'smooth'});}
function save(){if(window.planOrigin==='owner'){notify('This private plan is read-only. No changes were saved.');return}try{localStorage.setItem(KEY,JSON.stringify(plan));notify('Saved on this device. Export JSON to keep a backup.')}catch{notify('Browser storage is unavailable. Export JSON now to keep a copy.')}render()}
function download(obj,name){const blob=new Blob([JSON.stringify(obj,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
if($('start')) $('start').onclick=()=>{show(TEMPLATE,'blank');save()};$('import').onclick=()=>$('file').click();$('file').onchange=async e=>{const f=e.target.files?.[0];if(!f)return;if(f.size>5_000_000){alert('This file is larger than 5 MB. Please choose a smaller JSON plan.');return}try{show(JSON.parse(await f.text()),'import');save()}catch(err){alert('Could not open this plan: '+err.message)}e.target.value=''};
$('template').onclick=()=>download(TEMPLATE,'my-home-loan-empty-template.json');$('download').onclick=()=>{if(window.planOrigin==='owner'){notify('Private-plan export is disabled in this preview.');return}if(plan)download(plan,'my-home-loan-backup.json')};$('reset').onclick=()=>{if(window.planOrigin==='owner'){notify('Use Sign out to close your private plan.');return}if(!confirm('Close this plan and delete its saved copy from this browser? Export a backup first if you need it.'))return;localStorage.removeItem(KEY);plan=null;$('workspace').hidden=true;$('intro').hidden=false;window.scrollTo({top:0,behavior:'smooth'})};
document.querySelectorAll('.tabs button').forEach(b=>b.onclick=()=>{tab=b.dataset.tab;render()});
function card(label,value,sub=''){return `<div class="card"><label>${esc(label)}</label><strong>${esc(value)}</strong><small>${esc(sub)}</small></div>`}
function bars(rows){if(!rows.length)return '<div class="empty">No entries yet. Import a JSON plan to see the breakdown.</div>';const max=Math.max(1,...rows.map(x=>Number(x.value)||0));return rows.map(x=>`<div class="bar-row"><span>${esc(x.label)}</span><div class="bar"><i style="width:${Math.min(100,Math.max(0,(Number(x.value)||0)/max*100))}%"></i></div><b>${esc(money(x.value))}</b></div>`).join('')}
function table(rows,fields){if(!rows.length)return '<div class="empty">No records in this section yet.</div>';return `<div class="table-wrap"><table><thead><tr>${fields.map(f=>`<th>${esc(f.label)}</th>`).join('')}</tr></thead><tbody>${rows.map(row=>`<tr>${fields.map(f=>`<td>${esc(f.render?f.render(row):row[f.key])}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`}
const cost=()=>sum(plan.contractor)+sum(plan.indirectExpenses);
function overview(){const l=plan.loan,costPlanned=sum(plan.budget,'planned')+sum(plan.indirectBudget,'planned'),fund=sum(plan.funding,'planned'),out=Number(l.outstanding)||0,rate=Number(l.rate)||0;return `<div class="cards">${card('Project budget',money(costPlanned),'Construction + indirect')}${card('Paid to date',money(cost()),'Contractor + indirect')}${card('Loan outstanding',money(out),'Entered balance')}${card('Remaining budget',money(costPlanned-cost()),'Plan minus paid')}</div><div class="grid2"><div class="panel"><h3>Funding plan</h3>${bars(asArray(plan.funding).map(x=>({label:x.source||'Other',value:x.planned})))}</div><div class="panel"><h3>What needs attention</h3><p>Funding gap: <strong>${money(costPlanned-fund)}</strong> · ${costPlanned>fund?'planned budget exceeds listed sources':'planned sources cover listed budget'}</p><p>Processing stage: <span class="pill">${esc(plan.processing?.stage||'Not set')}</span></p><p>Interest rate: <strong>${esc(rate)}%</strong> · Entered lender: <strong>${esc(l.lender||'Not set')}</strong></p><p class="hint">Figures are only as current as the JSON you imported or the edits on this device.</p></div></div>`}
function ledger(){return `<div class="cards">${card('Contractor paid',money(sum(plan.contractor)),`${asArray(plan.contractor).length} entries`)}${card('Indirect costs',money(sum(plan.indirectExpenses)),`${asArray(plan.indirectExpenses).length} entries`)}${card('Disbursed',money(sum(plan.disbursements)),'Recorded disbursements')}${card('Prepaid',money(sum(plan.prepayments)),'Recorded extra payments')}</div><div class="panel"><h3>Contractor payments</h3>${table(asArray(plan.contractor),[{key:'date',label:'Date'},{key:'payee',label:'Payee'},{key:'category',label:'Category'},{key:'source',label:'Source'},{key:'amount',label:'Amount',render:x=>money(x.amount)}])}</div><div class="panel"><h3>Indirect expenses</h3>${table(asArray(plan.indirectExpenses),[{key:'date',label:'Date'},{key:'description',label:'Description'},{key:'category',label:'Category'},{key:'amount',label:'Amount',render:x=>money(x.amount)}])}</div>`}
function plans(){return `<div class="grid2"><div class="panel"><h3>Construction budget</h3>${bars(asArray(plan.budget).map(x=>({label:x.category||'Other',value:x.planned})))}</div><div class="panel"><h3>Indirect cost budget</h3>${bars(asArray(plan.indirectBudget).map(x=>({label:x.category||'Other',value:x.planned})))}</div></div><div class="panel"><h3>Funding sources</h3>${table(asArray(plan.funding),[{key:'source',label:'Source'},{key:'note',label:'Notes'},{key:'planned',label:'Planned',render:x=>money(x.planned)}])}</div>`}
function sim(balance,rate,years,extra){const r=rate/1200,months=Math.max(1,Math.round(years*12));if(balance<=0||years<=0||rate<0||rate>100)return null;const emi=r?balance*r/(1-(1+r)**(-months)):balance/months;if(!Number.isFinite(emi))return null;let b=balance,interest=0,m=0;while(b>.01&&m<1200){let charge=b*r;interest+=charge;const payment=Math.min(b+charge,emi+extra);b=Math.max(0,b+charge-payment);m++;if(payment<=charge)return null}return {emi,interest,months:m,finish:b<.01}}
function schedule(){let l=plan.loan;return `<div class="panel"><h3>Loan payoff scenario</h3><p class="hint">Uses a fixed monthly rate for an estimate, not the lender's actual floating-rate or construction-linked schedule. It starts from the balance entered below, not sanctioned amount; excludes fees and future disbursements.</p><div class="fields"><label>Outstanding balance (₹)<input id="outstanding" type="number" min="0" value="${esc(l.outstanding||0)}"></label><label>Annual interest (%)<input id="rate" type="number" min="0" max="100" step=".01" value="${esc(l.rate||0)}"></label><label>Remaining term (years)<input id="tenureYears" type="number" min=".1" max="100" step=".1" value="${esc(l.tenureYears||15)}"></label><label>Extra each month (₹)<input id="extraMonthly" type="number" min="0" value="${esc(l.extraMonthly||0)}"></label></div><button class="primary" id="calculate">Update scenario</button><div id="simulation"></div></div>`}
function updateSimulation(){const l=plan.loan,b=Number(l.outstanding),r=Number(l.rate),y=Number(l.tenureYears),extra=Number(l.extraMonthly),base=sim(b,r,y,0),scenario=sim(b,r,y,extra);$('simulation').innerHTML=(!base||!scenario)?'<p class="alert">Enter a positive outstanding balance and a valid interest rate/term to compare payments.</p>':`<div class="cards" style="margin-top:22px">${card('Baseline EMI',money(base.emi),'Constant-rate estimate')}${card('Baseline payoff',`${base.months} months`,money(base.interest)+' interest')}${card('With extra payment',`${scenario.months} months`,money(scenario.interest)+' interest')}${card('Estimated saving',money(base.interest-scenario.interest),`${base.months-scenario.months} months earlier`)}</div><p class="hint">Rate changes, payment dates, lender rounding and future disbursements will change actual results.</p>`}
function records(){return `<div class="grid2"><div class="panel"><h3>Emergency reserve</h3><p>Current: <strong>${money(plan.emergency?.currentFund)}</strong></p><p>Target: <strong>${money(Number(plan.emergency?.monthlyEssentials||0)*Number(plan.emergency?.targetMonths||0))}</strong></p></div><div class="panel"><h3>Project details</h3><p>${esc(plan.loan.notes||'No project notes entered.')}</p></div></div><div class="panel"><h3>Family records</h3>${table(asArray(plan.family),[{key:'name',label:'Name'},{key:'relation',label:'Relation'},{key:'dependency',label:'Dependency'}])}</div><div class="panel"><h3>Insurance cover</h3>${table(asArray(plan.insurance),[{key:'name',label:'Name'},{key:'type',label:'Type'},{key:'sumInsured',label:'Cover',render:x=>money(x.sumInsured)}])}</div><div class="panel"><h3>Actions</h3>${table(asArray(plan.actions),[{key:'description',label:'Action'},{key:'status',label:'Status'}])}</div>`}
function render(){if(!plan)return;document.querySelectorAll('.tabs button').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));$('view').innerHTML=({overview,ledger,plans,schedule,records}[tab])();if(tab==='schedule'){if(window.planOrigin==='owner')$('calculate').disabled=true;$('calculate').onclick=()=>{if(window.planOrigin==='owner'){notify('Private plan is read-only in this preview.');return}for(const k of ['outstanding','rate','tenureYears','extraMonthly']){let n=Number($(k).value);if(!Number.isFinite(n)||n<0){notify('Enter non-negative numbers.');return}plan.loan[k]=n}save()};updateSimulation()}}
try{const stored=localStorage.getItem(KEY);if(stored){show(JSON.parse(stored),'saved');notify('This browser has a saved plan. It has not been uploaded.')}}catch{localStorage.removeItem(KEY)}
// Editable local plan. Additions are saved only on this device and to explicit downloads.
const editFields={loan:[['lender','Lender','text'],['loanAccountNumber','Loan account number','text'],['projectCost','Project cost (₹)','number'],['sanctioned','Sanctioned loan (₹)','number'],['disbursed','Total disbursed (₹)','number'],['outstanding','Outstanding loan (₹)','number'],['rate','Annual rate (%)','number'],['tenureYears','Remaining term (years)','number'],['repaymentStart','Repayment start','date'],['emiDueDay','EMI due day','number'],['extraMonthly','Extra monthly payment (₹)','number'],['notes','Project notes','text']],emergency:[['monthlyEssentials','Monthly essentials (₹)','number'],['targetMonths','Reserve months','number'],['currentFund','Current reserve (₹)','number']]};
const entryFields={contractor:[['date','Date','date'],['payee','Payee','text'],['category','Category','text'],['amount','Amount (₹)','number'],['source','Funding source','text'],['mode','Payment mode','text'],['note','Reference / note','text']],indirectExpenses:[['date','Date','date'],['description','Description','text'],['category','Category','text'],['amount','Amount (₹)','number'],['source','Funding source','text']],budget:[['category','Category','text'],['planned','Budget (₹)','number']],indirectBudget:[['category','Category','text'],['planned','Budget (₹)','number']],funding:[['source','Source','text'],['planned','Planned (₹)','number']],disbursements:[['date','Date','date'],['amount','Amount (₹)','number'],['note','Reference / note','text']],prepayments:[['date','Date','date'],['amount','Amount (₹)','number'],['note','Reference / note','text']],actions:[['description','Action','text'],['status','Status','text']],insurance:[['name','Policy name','text'],['type','Type','text'],['provider','Provider','text'],['sumInsured','Cover (₹)','number'],['premium','Premium (₹)','number'],['renewal','Renewal','date']],family:[['name','Name','text'],['relation','Relationship','text'],['dependency','Dependency','text']]};
function fieldsFor(def,prefix,obj){return def.map(([key,label,type])=>`<label>${esc(label)}<input data-key="${esc(key)}" id="${prefix}${esc(key)}" type="${type}" ${type==='number'?'min="0" step="any"':''} value="${esc(obj?.[key]??'')}"></label>`).join('')}
function edit(){return `<div class="panel"><h3>Loan details</h3><div class="editor">${fieldsFor(editFields.loan,'loan-',plan.loan)}</div><div class="editor-actions"><button class="primary" id="save-loan">Save loan details</button></div></div><div class="panel"><h3>Emergency reserve</h3><div class="editor">${fieldsFor(editFields.emergency,'emergency-',plan.emergency||{})}</div><div class="editor-actions"><button class="primary" id="save-emergency">Save reserve</button></div></div><div class="panel"><h3>Ledger and planning entries</h3><p class="hint">Add an entry to your plan, then export a backup. Editing a JSON import stays local to this browser. Frozen records from an imported plan are read-only here; change them in your source of truth.</p><label>Section<select id="entry-section">${Object.keys(entryFields).map(k=>`<option value="${k}">${esc(({indirectExpenses:'Indirect expenses',indirectBudget:'Indirect budget'}[k]||k))}</option>`).join('')}</select></label><div id="entry-fields" class="editor" style="margin-top:20px"></div><div class="editor-actions"><button class="primary" id="add-entry">Add entry</button></div><div id="entry-list"></div></div>`}
function mountEdit(){for(const section of Object.keys(editFields)){$('save-'+section).onclick=()=>{const obj=plan[section]||(plan[section]={});for(const [key,label,type] of editFields[section]){const val=$(section+'-'+key).value;if(type==='number'&&(!Number.isFinite(Number(val))||Number(val)<0)){notify(`${label} must be a non-negative number.`);return}obj[key]=type==='number'?Number(val):val}save()}}const selector=$('entry-section');function updateSection(){const section=selector.value,def=entryFields[section];$('entry-fields').innerHTML=fieldsFor(def,'entry-',{});const rows=asArray(plan[section]);$('entry-list').innerHTML=rows.length?`<div class="table-wrap"><table><thead><tr>${def.map(x=>`<th>${esc(x[1])}</th>`).join('')}<th></th></tr></thead><tbody>${rows.map((row,i)=>`<tr>${def.map(([key,,type])=>`<td>${esc(type==='number'?money(row[key]):row[key])}</td>`).join('')}<td>${row.frozen?'<span class="pill">Frozen</span>':`<button class="row-delete" data-index="${i}">Remove</button>`}</td></tr>`).join('')}</tbody></table></div>`:'<div class="empty-state">No entries yet.</div>';$('entry-list').querySelectorAll('button[data-index]').forEach(b=>b.onclick=()=>{if(!confirm('Remove this entry?'))return;plan[section].splice(Number(b.dataset.index),1);save()})}selector.onchange=updateSection;updateSection();$('add-entry').onclick=()=>{const section=selector.value,row={};for(const [key,label,type] of entryFields[section]){const value=$('entry-'+key).value;if(type==='number'&&(!Number.isFinite(Number(value))||Number(value)<0)){notify(`${label} must be a non-negative number.`);return}row[key]=type==='number'?Number(value):value}if(!Object.values(row).some(v=>v&&v!==0)){notify('Enter at least one field to add an entry.');return}plan[section]=asArray(plan[section]);plan[section].push(row);save()}}
// Replace the first render implementation with an extension preserving the existing views.
const originalRender=render;
render=function(){if(!plan)return;if(tab==='edit'&&window.planOrigin==='owner'){tab='overview';notify('Private plan is read-only in this preview.')}if(tab==='edit'){document.querySelectorAll('.tabs button').forEach(b=>b.classList.toggle('active',b.dataset.tab===tab));$('view').innerHTML=edit();mountEdit()}else originalRender()};

window.show=show;window.clearLoadedPlan=()=>{plan=null;document.getElementById('workspace').hidden=true;document.getElementById('intro').hidden=false};
